// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_5000 = "CgkI-uvij_8EEAIQKA"; // <GPGSID>
        public const string achievement_beagle = "CgkI-uvij_8EEAIQLQ"; // <GPGSID>
        public const string achievement_2000 = "CgkI-uvij_8EEAIQJw"; // <GPGSID>
        public const string achievement_500_3 = "CgkI-uvij_8EEAIQOA"; // <GPGSID>
        public const string achievement_18 = "CgkI-uvij_8EEAIQEg"; // <GPGSID>
        public const string achievement_19 = "CgkI-uvij_8EEAIQEw"; // <GPGSID>
        public const string achievement_word_search = "CgkI-uvij_8EEAIQMw"; // <GPGSID>
        public const string achievement_20000 = "CgkI-uvij_8EEAIQKg"; // <GPGSID>
        public const string achievement = "CgkI-uvij_8EEAIQFg"; // <GPGSID>
        public const string achievement_gold_chicken = "CgkI-uvij_8EEAIQLw"; // <GPGSID>
        public const string achievement_300 = "CgkI-uvij_8EEAIQGw"; // <GPGSID>
        public const string achievement_doberman = "CgkI-uvij_8EEAIQLg"; // <GPGSID>
        public const string achievement_300_3 = "CgkI-uvij_8EEAIQNw"; // <GPGSID>
        public const string achievement_300_2 = "CgkI-uvij_8EEAIQJA"; // <GPGSID>
        public const string achievement_10_3 = "CgkI-uvij_8EEAIQIA"; // <GPGSID>
        public const string achievement_beta_tester = "CgkI-uvij_8EEAIQFw"; // <GPGSID>
        public const string achievement_100000_2 = "CgkI-uvij_8EEAIQPA"; // <GPGSID>
        public const string achievement_2 = "CgkI-uvij_8EEAIQMQ"; // <GPGSID>
        public const string achievement_3 = "CgkI-uvij_8EEAIQMg"; // <GPGSID>
        public const string achievement_6 = "CgkI-uvij_8EEAIQBg"; // <GPGSID>
        public const string achievement_7 = "CgkI-uvij_8EEAIQBw"; // <GPGSID>
        public const string achievement_4 = "CgkI-uvij_8EEAIQBA"; // <GPGSID>
        public const string achievement_5 = "CgkI-uvij_8EEAIQBQ"; // <GPGSID>
        public const string achievement_500 = "CgkI-uvij_8EEAIQHA"; // <GPGSID>
        public const string achievement_8 = "CgkI-uvij_8EEAIQCA"; // <GPGSID>
        public const string achievement_9 = "CgkI-uvij_8EEAIQCQ"; // <GPGSID>
        public const string achievement_20_2 = "CgkI-uvij_8EEAIQIQ"; // <GPGSID>
        public const string achievement_malinois = "CgkI-uvij_8EEAIQLA"; // <GPGSID>
        public const string achievement_10_2 = "CgkI-uvij_8EEAIQGA"; // <GPGSID>
        public const string achievement_5000_2 = "CgkI-uvij_8EEAIQOg"; // <GPGSID>
        public const string achievement_1000 = "CgkI-uvij_8EEAIQHQ"; // <GPGSID>
        public const string leaderboard_3 = "CgkI-uvij_8EEAIQPg"; // <GPGSID>
        public const string achievement_10000_2 = "CgkI-uvij_8EEAIQKQ"; // <GPGSID>
        public const string achievement_12 = "CgkI-uvij_8EEAIQDA"; // <GPGSID>
        public const string achievement_20_3 = "CgkI-uvij_8EEAIQNA"; // <GPGSID>
        public const string achievement_17 = "CgkI-uvij_8EEAIQEQ"; // <GPGSID>
        public const string leaderboard_4 = "CgkI-uvij_8EEAIQPw"; // <GPGSID>
        public const string achievement_14 = "CgkI-uvij_8EEAIQDg"; // <GPGSID>
        public const string leaderboard_5 = "CgkI-uvij_8EEAIQQA"; // <GPGSID>
        public const string achievement_15 = "CgkI-uvij_8EEAIQDw"; // <GPGSID>
        public const string achievement_100000 = "CgkI-uvij_8EEAIQHw"; // <GPGSID>
        public const string achievement_1000_3 = "CgkI-uvij_8EEAIQOQ"; // <GPGSID>
        public const string leaderboard_2 = "CgkI-uvij_8EEAIQPQ"; // <GPGSID>
        public const string achievement_100_3 = "CgkI-uvij_8EEAIQNg"; // <GPGSID>
        public const string achievement_100_2 = "CgkI-uvij_8EEAIQIg"; // <GPGSID>
        public const string achievement_20 = "CgkI-uvij_8EEAIQFA"; // <GPGSID>
        public const string achievement_10 = "CgkI-uvij_8EEAIQCg"; // <GPGSID>
        public const string achievement_11 = "CgkI-uvij_8EEAIQCw"; // <GPGSID>
        public const string leaderboard = "CgkI-uvij_8EEAIQAQ"; // <GPGSID>
        public const string achievement_16 = "CgkI-uvij_8EEAIQEA"; // <GPGSID>
        public const string achievement_10000 = "CgkI-uvij_8EEAIQHg"; // <GPGSID>
        public const string achievement_10_4 = "CgkI-uvij_8EEAIQMA"; // <GPGSID>
        public const string achievement_50 = "CgkI-uvij_8EEAIQGQ"; // <GPGSID>
        public const string achievement_10000_3 = "CgkI-uvij_8EEAIQOw"; // <GPGSID>
        public const string leaderboard_6 = "CgkI-uvij_8EEAIQQQ"; // <GPGSID>
        public const string achievement_1000_2 = "CgkI-uvij_8EEAIQJg"; // <GPGSID>
        public const string achievement_50_2 = "CgkI-uvij_8EEAIQIw"; // <GPGSID>
        public const string achievement_50_3 = "CgkI-uvij_8EEAIQNQ"; // <GPGSID>
        public const string achievement_22 = "CgkI-uvij_8EEAIQFQ"; // <GPGSID>
        public const string achievement_100 = "CgkI-uvij_8EEAIQGg"; // <GPGSID>
        public const string achievement_500_2 = "CgkI-uvij_8EEAIQJQ"; // <GPGSID>
        public const string achievement_13 = "CgkI-uvij_8EEAIQDQ"; // <GPGSID>

}

